language: python
sudo: false
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"

before_install:
  - pip install -r requirements-dev.txt
  - pip install -r requirements.txt

arch:
  - amd64
  - arm64

install:
  - python setup.py develop

script:
  - pytest --cov=geocoder tests

after_success:
  - codecov

notifications:
  email:
    - carriere.denis@gmail.com
